### PR TITLE
Added environment variable for allowing only specific URLs

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**
When the environment variable `SAFEIMPORTS_URL_ALLOWLIST` is set all URLs will be disallowed by default and only those defined on the allowlist will be allowed.

When both the blocklist environment variable `SAFEIMPORTS_URL_BLACKLIST` and the new allowlist environment variable are defined, the blocklist environment variable will have a higher priority than the allowlist, allowing for fine-grained control over allowed and disallowed URLs.

There should be some more documentation on the allowing and blocking of URLs, however this should be covered in a separate PR

### CODE REVIEW

**Comment by JeffersonBledsoe** [comment]
> @JeffersonBledsoe The right place to do this is your layer tear down, or the unittest. for doctests there is a python file which creates the testsuite. that would be the best place to put this code

@djay The reason I put the environment deletion at the end of that set of tests rather than the test cleanup is because future tests can just be appended to the end of the file. From what I can gather, the doctests are isolated and so the whole test should be cleaned up correctly once it has finished anyway. Do correct me if I'm wrong!

**Comment by djay** [comment]
@JeffersonBledsoe having many unrelated tests in one .txt file is a bad idea. In fact I'd rather get away from doctests in a .txt file all together. You can just as easily put multiple in a .py file and that helps you think of testing smaller units of functionality. The reason why you want to have seperate isolated tests is that 

a) it makes it easier to maintain 
b) the test method names often make it easier to see what broke more quickly. 
c) tests always finish on the first failure so one failure doesn't hide other failures so you can know sooner if you caused multiple problems or not and estimate time better.

**Comment by djay** [comment]
@JeffersonBledsoe in this case we are using .txt files because we want to be cheap and reuse it as documentation. I would still put in a general case teardown to remove those environment variables so tests don't intereact but I guess there is no harm in also removing the vars there in case someone wants to put more documentation in

**Comment by JeffersonBledsoe** [comment]
> @JeffersonBledsoe in this case we are using .txt files because we want to be cheap and reuse it as documentation. I would still put in a general case teardown to remove those environment variables so tests don't intereact but I guess there is no harm in also removing the vars there in case someone wants to put more documentation in

@djay Each test file is isolated so there's no need to clear the environment variables ourselves.

As for moving away from using rst files as both tests and documentation, I would agree, however that's probably best saved for another PR.

Anything else need doing to this or is it good to be merged?

**Comment by JeffersonBledsoe** [comment]
@djay We okay to merge this? It works fine for the tests I provided, but doesn't seem to work for the [requests PR](https://github.com/collective/collective.trustedimports/pull/23). I think that is requests specific though rather than an issue with the PR.

**Review by djay — APPROVED** [review]

**Pull request merged**
